"""Add Phase 8 Incident columns

Revision ID: 6d7f374e573b
Revises: 65efd7081045
Create Date: 2026-05-21 07:13:31.677123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7f374e573b'
down_revision: Union[str, Sequence[str], None] = '65efd7081045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident', sa.Column('severity', sa.Integer(), nullable=False))
    op.add_column('incident', sa.Column('confidence_score', sa.Float(), nullable=False))
    op.add_column('incident', sa.Column('ward_id', sa.Integer(), nullable=True))
    op.add_column('incident', sa.Column('ward_name', sa.String(), nullable=True))
    op.add_column('incident', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incident', 'timestamp')
    op.drop_column('incident', 'ward_name')
    op.drop_column('incident', 'ward_id')
    op.drop_column('incident', 'confidence_score')
    op.drop_column('incident', 'severity')
    # ### end Alembic commands ###
